OPENRGB_ENABLE = no
MOUSEKEY_ENABLE = yes
OS_DETECTION_ENABLE = yes
VIA_ENABLE = no
DYNAMIC_MACRO_ENABLE = yes

# For smaller firmware size
LTO_ENABLE = yes
QMK_SETTINGS = no
TAP_DANCE_ENABLE = no
COMBO_ENABLE = no
KEY_OVERRIDE_ENABLE = no
