MOUSEKEY_ENABLE = yes
OS_DETECTION_ENABLE = yes
VIA_ENABLE = no
DYNAMIC_MACRO_ENABLE = yes
TAP_DANCE_ENABLE = no

# For smaller firmware size
#LTO_ENABLE = yes
#QMK_SETTINGS = no
#COMBO_ENABLE = no
#KEY_OVERRIDE_ENABLE = no
