// Copyright 2024 Danny Nguyen (@nooges)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#if defined(KEYBOARD_keebio_quefrency_rev1)
    // Set 65% column (option 1) and Macro (option 2) on by default
    #define VIA_EEPROM_LAYOUT_OPTIONS_DEFAULT 0x60

#elif defined(KEYBOARD_keebio_quefrency_rev2)
    // Set 65% column (option 3) and Macro (option 4) on by default
    #define VIA_EEPROM_LAYOUT_OPTIONS_DEFAULT 0x00DE
    #define VIA_EEPROM_LAYOUT_OPTIONS_SIZE 2

#elif defined(KEYBOARD_keebio_quefrency_rev3)
    // Set 65% column (option 3) and Macro (option 4) on by default
    #define VIA_EEPROM_LAYOUT_OPTIONS_DEFAULT 0x00DE
    #define VIA_EEPROM_LAYOUT_OPTIONS_SIZE 2

#elif defined(KEYBOARD_keebio_quefrency_rev6)
    #define VIA_EEPROM_LAYOUT_OPTIONS_SIZE 2

#endif

#define RGB_MATRIX_TIMEOUT 120000
// #define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_SOLID_COLOR
// #define RGB_MATRIX_DEFAULT_HUE 85
// #define RGB_MATRIX_DEFAULT_SAT 255
// #define RGB_MATRIX_DEFAULT_VAL 255

// #undef ENABLE_RGB_MATRIX_ALPHAS_MODS
// #undef ENABLE_RGB_MATRIX_BAND_SAT
// #undef ENABLE_RGB_MATRIX_BAND_VAL
// #undef ENABLE_RGB_MATRIX_BAND_PINWHEEL_SAT
// #undef ENABLE_RGB_MATRIX_BAND_PINWHEEL_VAL
// #undef ENABLE_RGB_MATRIX_BAND_SPIRAL_SAT
// #undef ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL
// #undef ENABLE_RGB_MATRIX_BREATHING
// #undef ENABLE_RGB_MATRIX_CYCLE_ALL
// #undef ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
// #undef ENABLE_RGB_MATRIX_CYCLE_OUT_IN
// #undef ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
// #undef ENABLE_RGB_MATRIX_CYCLE_PINWHEEL
// #undef ENABLE_RGB_MATRIX_CYCLE_SPIRAL
// #undef ENABLE_RGB_MATRIX_CYCLE_UP_DOWN
// #undef ENABLE_RGB_MATRIX_DIGITAL_RAIN
// #undef ENABLE_RGB_MATRIX_DUAL_BEACON
// #undef ENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT
// #undef ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN
// #undef ENABLE_RGB_MATRIX_HUE_BREATHING
// #undef ENABLE_RGB_MATRIX_HUE_PENDULUM
// #undef ENABLE_RGB_MATRIX_HUE_WAVE
// #undef ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
// #undef ENABLE_RGB_MATRIX_MULTISPLASH
// #undef ENABLE_RGB_MATRIX_PIXEL_FLOW
// #undef ENABLE_RGB_MATRIX_PIXEL_FRACTAL
// #undef ENABLE_RGB_MATRIX_PIXEL_RAIN
// #undef ENABLE_RGB_MATRIX_RAINBOW_BEACON
// #undef ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
// #undef ENABLE_RGB_MATRIX_RAINBOW_PINWHEELS
// #undef ENABLE_RGB_MATRIX_RAINDROPS
// #undef ENABLE_RGB_MATRIX_SOLID_MULTISPLASH
// #undef ENABLE_RGB_MATRIX_SOLID_REACTIVE
// #undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS
// #undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS
// #undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS
// #undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
// #undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS
// #undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
// #undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE
// #undef ENABLE_RGB_MATRIX_SOLID_SPLASH
// #undef ENABLE_RGB_MATRIX_SPLASH
// #undef ENABLE_RGB_MATRIX_TYPING_HEATMAP

// #define ENABLE_RGB_MATRIX_PIXEL_RAIN

#undef MASTER_LEFT
#undef MASTER_RIGHT
#define EE_HANDS

#define SPLIT_TRANSACTION_IDS_USER RPC_SYNC

#define SPLIT_LAYER_STATE_ENABLE // Leave at the bottom for some reason
